sudo: required
services:
  - docker

before_install:
  - docker build -t kalle1337/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kalle1337/react-test npm test

after_success:
  - docker build -t kalle1337/multi-client ./client
  - docker build -t kalle1337/multi-nginx ./nginx
  - docker build -t kalle1337/multi-server ./server
  - docker build -t kalle1337/multi-worker ./worker

  # login to docker:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kalle1337/multi-client
  - docker push kalle1337/multi-nginx
  - docker push kalle1337/multi-server
  - docker push kalle1337/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  